name: go release

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    uses: bavix/.github/.github/workflows/go-release-binary.yml@0.4.0
    with:
      executable_compression: upx -v -9
